//cliente para hacer peticiones al servidor
//complemento rest client
GET http://localhost:35000/api/estudiantes

###
POST http://localhost:35000/api/estudiantes
Content-Type: application/json

{
    "nombre": "Toño Coto",
    "correo": "toño@correo.de",
    "activo": true
}

###
GET http://localhost:35000/api/estudiantes/605244d14d51c30d94d81a88

###
DELETE  http://localhost:35000/api/estudiantes/60521b050b609f2f9c9fca02

###
GET http://localhost:35000/api/estudiantes/activos

###
PUT   http://localhost:35000/api/estudiantes/605244d14d51c30d94d81a88
Content-Type: application/json

{   
    "nombre": "Jimena Lorena",
    "activo": false
}
